service: s3-album

provider:
  name: aws
  runtime: java8
  timeout: 300
  memorySize: 1536
  logRetentionInDays: 7
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: yyna-lambda-deployments
  environment:
    AWS_S3_BUCKET_NAME: ${file(config.${opt:stage, 'dev'}.json):AWS_S3_BUCKET_NAME}

package:
  artifact: ${file(build/build.json):distribution}

functions:
  list-objects:
    handler: list_objects::handler
    tags:
      VERSION: ${file(build/build.json):version}